HEBREW_PREPOSITIONS = ["וב","מ", "ל", "ב", "ו","מה","ה"]
LOCATION_PREPOSITIONS = HEBREW_PREPOSITIONS
DISEASE_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICATION_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICAL_TEST_PREPOSITIONS = HEBREW_PREPOSITIONS
