HEBREW_PREPOSITIONS = ["מה","מ", "ל", "ב", "ו","וב","ה"]
LOCATION_PREPOSITIONS = HEBREW_PREPOSITIONS
DISEASE_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICATION_PREPOSITIONS = HEBREW_PREPOSITIONS
MEDICAL_TEST_PREPOSITIONS = HEBREW_PREPOSITIONS
